#' @include rvatResult.R

## Methods ---------------------------------------------------------------------

### Reading & Writing ----------------------------------------------------------

#' readGsaResults
#' 
#' Read results generated using the \code{\link{geneSetAssoc}} method.

#' @param path File path to data
#' @param header A logical value indicating whether the data contains a header. Defaults to `TRUE`.
#' @param sep The field separator. Defaults to `\\t`, which is the default separator using in \code{\link{geneSetAssoc}}.
#' @return An object of type \code{\link{gsaResult}}.
#' @export
readGsaResults <- function(path, header = TRUE, sep = "\t") {
  
  if (header) {
    cols <- read.table(path, header = TRUE, nrows = 1, sep = sep)
    cols <- colnames(cols)
    
    if(mean(names(columns_gsaResults) %in% cols) < 1) {
      stop("The following columns are missing:
             %s
             ", 
           names(columns_gsaResults)[!names(columns_gsaResults) %in% cols]
      )
    }
    
    dat <- read.table(file = path,
                      header = TRUE,
                      sep = sep,
                      stringsAsFactors = FALSE)
    
  } else {
    dat <- read.table(file = path,
                      header = FALSE,
                      sep = sep,
                      stringsAsFactors = FALSE)
    
    if (ncol(dat) > length(columns_gsaResults)) {
      message(sprintf("Number of columns is larger than the default, assuming that the first %s columns 
are the default gsaResult columns.",length(columns_gsaResults)))
      colnames(dat)[1:length(columns_gsaResults)] <- name(columns_gsaResults)
    } else {
      colnames(dat) <- names(columns_gsaResults)
    }
  }
  
  dat[,columns_gsaResults_numeric] <- lapply(dat[,columns_gsaResults_numeric],
                                             as.numeric)
  
  dat$threshold <- as.numeric(dat$threshold)    
  
  dat[,columns_gsaResults_rle] <- lapply(dat[,columns_gsaResults_rle],
                                         as.character)
  dat <- gsaResult(dat)
  
  dat
}

# gsaResult --------------------------------------------------------------------

## constructor --------------------------------------------------

# Constructor
proto_gsaResult <- S4Vectors::DataFrame(
  geneSetName =Rle(character(0)),
  test = Rle(character(0)),
  covar = character(),
  threshold = numeric(),
  geneSetSize = numeric(),
  genesObs = numeric(),
  P = numeric(),
  effect = numeric(),
  effectSE = numeric(),
  effectCIlower = numeric(),
  effectCIupper = numeric()
)

#' Create a \code{\link{gsaResult-class}}
#'
#' @param object gsa results as generated by the \code{\link{geneSetAssoc}} method.
#' Can be either a data.frame or a filepath pointing to the results.
#' @param header Relevant if `object` is a filepath, does the data contain a header? (TRUE/FALSE).
#' @export
gsaResult <- function(object, header = TRUE) {
  if(missing(object)) {
    object <- proto_gsaResult
  } 
  
  if (is.character(object)) {
    readGsaResults(path = object, header = header, sep = "\t")
  } else if ( is.data.frame(object) || is(object, "DFrame")) {
    if (!all(names(columns_gsaResults) %in% colnames(object))) {
      stop(sprintf("The following columns are missing: %s", 
                   paste(names(columns_gsaResults)[!names(columns_gsaResults) %in% colnames(object)], collapse=",")))
    }
    object <- cbind(object[,names(columns_gsaResults)], object[,!colnames(object) %in% names(columns_gsaResults), drop = FALSE])
    if(is.data.frame(object)) object <- S4Vectors::DataFrame(object)
    object[,columns_gsaResults_rle] <- lapply(object[,columns_gsaResults_rle], S4Vectors::Rle)
    object[,columns_gsaResults_numeric] <- lapply(object[,columns_gsaResults_numeric], as.numeric)
    
    
    #Addition to make the 'threshold' column numeric, as this was not the case in the test object
    object$threshold <- as.numeric(object$threshold)
    new("gsaResult", object)
    
  } else {
    stop("`object` should be either a data.frame/DataFrame or a filepath.")
  }
}

# validity
setValidity2("gsaResult", function(object) {
  msg <- NULL
  
  if (!all(names(columns_gsaResults) %in% colnames(object)) && ncol(object) != 1) {
    msg <- c(msg, sprintf("The following columns are missing: %s",
                          paste(names(columns_gsaResults)[!names(columns_gsaResults) %in% colnames(object)], collapse=",")))
  }
  
  if(ncol(object) != 1) {
    columns <- names(columns_gsaResults)[names(columns_gsaResults) %in% colnames(object)]
    types <- unlist(lapply(object@listData, class))
    type_check <- unlist(lapply(columns, FUN = function(x) types[x] %in% columns_gsaResults[[x]]))
    names(type_check) <- columns
    if (!all(type_check) && ncol(object) != 1) {
      type_msg <- lapply(
        names(type_check)[!type_check], FUN = function(x) sprintf("%s: %s", x, paste(columns_gsaResults[[x]], collapse=" or "))
      ) %>% paste(collapse="\n")
      msg <- c(msg,sprintf("The following columns should be of type:\n%s", type_msg))
    }
  }
  
  if (is.null(msg)) {
    TRUE
  } else msg
})

## Methods ---------------------------------------------------------------------

### Summary --------------------------------------------------------------------

#' @describeIn gsaResult summary
#' @param object \code{\link{gsaResult}} object
#' @param asList If `TRUE`, will return a list rather than printing to the console.
#' Defaults to `FALSE`.
#' @export
setMethod("summary", "gsaResult",
          function(object, asList=FALSE, ...)
          {
            info <- list()
            info[["Ngenesets"]] <- length(unique(object[["geneSetName"]]))
            info[["tests"]] <- unique(object[["test"]])
            info[["covar"]] <- unique(object[["covar"]])
            
            if(asList) {
              return(info)
            } else {
              cat(sprintf("%s object\n-------------------\n", class(object)[1]))
              cat(sprintf("n gene sets = %s\ntests = %s\ncovar = %s", 
                          info$Ngenesets,
                          paste(info[["tests"]],collapse=","), 
                          paste(info[["covar"]],collapse=",")
              ))
            }
          })